module.exports = {
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/src/setup-jest.ts'],
  testPathIgnorePatterns: ['<rootDir>/node_modules/', '<rootDir>/dist/', '<rootDir>/src/test.ts'],
  coverageDirectory: '<rootDir>/coverage/',
  coverageReporters: ['html', 'lcov', 'text-summary', 'json-summary'],
  collectCoverageFrom: [
    '<rootDir>/src/**/*.ts',
    '!<rootDir>/src/main.ts',
    '!<rootDir>/src/main.server.ts',
    '!<rootDir>/src/server.ts',
    '!<rootDir>/src/app/app.config.server.ts',
    '!<rootDir>/src/app/core/app.config.ts',
    '!<rootDir>/src/app/core/core.module.ts',
    '!<rootDir>/src/app/shared/components/modal/modal.module.ts',
    '!<rootDir>/src/environments/*.ts',
    '!<rootDir>/**/index.ts',
    '!<rootDir>/**/public-api.ts',
    '!<rootDir>/src/app/shared/mocks/**',
    '!<rootDir>/**/models/**',
    '!<rootDir>/**/interfaces/**',
    '!<rootDir>/**/types/**',
    '!<rootDir>/**/constants.ts',
    '!<rootDir>/**/test-doubles.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90,
    },
  },
};
