[build]
  command = "npm ci && npm run build"
  publish = "dist/restaurante-frontend/browser"

[build.environment]
  NODE_VERSION = "20.16.0"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy a backend local durante `netlify dev` y/o deploy previews
[[redirects]]
  from = "/restaurante/v1/*"
  to = "http://localhost:8080/restaurante/v1/:splat"
  status = 200
  force = true

# Headers de seguridad globales
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(self), camera=(self), microphone=()"
    # CSP relajada para desarrollo/preview (permite eval e incluye backend local)
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https: http://localhost:8080; frame-src 'self' https://www.google.com https://maps.google.com; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'self';"

# HSTS solo para producci칩n
[context.production.headers]
  for = "/*"
  [context.production.headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    # CSP endurecida para producci칩n (sin unsafe-eval). Se permite backend local para pruebas en WebView.
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https: blob:; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https: http://localhost:8080; frame-src 'self' https://www.google.com https://maps.google.com; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'self';"

# Deploy Previews / Branch deploys: evitar indexaci칩n por buscadores
[context.deploy-preview.headers]
  for = "/*"
  [context.deploy-preview.headers.values]
    X-Robots-Tag = "noindex, nofollow"

[context.branch-deploy.headers]
  for = "/*"
  [context.branch-deploy.headers.values]
    X-Robots-Tag = "noindex, nofollow"

# Cache de assets est치ticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
