[build]
  command = "npm ci && npm run build"
  publish = "dist/restaurante-frontend/browser"

[build.environment]
  NODE_VERSION = "20.16.0"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy a backend local durante `netlify dev` y/o deploy previews
[[redirects]]
  from = "/restaurante/v1/*"
  to = "http://localhost:8080/restaurante/v1/:splat"
  status = 200
  force = true

# Headers de seguridad globales
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https: http://localhost:8080; base-uri 'self'; form-action 'self'; frame-ancestors 'self';"

# HSTS solo para producción
[context.production.headers]
  for = "/*"
  [context.production.headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

# Cache de assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
