name: CI
on:
  pull_request:
  push:
    branches: [master, develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm install --legacy-peer-deps
      - run: npm run lint
      - run: npm run lint:scss
      - run: npm test -- --ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - run: npm run build
      - name: Smoke Tests
        run: npm run smoke:test

      - name: Security Audit
        run: npm run security:audit

      - name: Bundle Size Check
        run: |
          # Verificar que el bundle inicial no sea demasiado grande (< 2MB)
          MAIN_SIZE=$(stat -c%s dist/restaurante-frontend/browser/main-*.js)
          if [ $MAIN_SIZE -gt 2097152 ]; then
            echo "ERROR: Main bundle too large: $MAIN_SIZE bytes (> 2MB)"
            exit 1
          fi
          echo "OK: Bundle size OK: $MAIN_SIZE bytes"
