name: Deploy Netlify
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Generate runtime app-config.json from secrets
        run: |
          API="${{ secrets.APP_API_BASE }}"
          GMAPS="${{ secrets.GMAPS_API_KEY }}"
          if [ -z "$API" ]; then API="/restaurante/v1"; fi
          echo '{' > public/app-config.json
          echo "  \"apiBase\": \"${API}\"" >> public/app-config.json
          if [ -n "$GMAPS" ]; then
            echo "  ,\"googleMapsApiKey\": \"${GMAPS}\"" >> public/app-config.json
          fi
          echo '}' >> public/app-config.json
      - run: npm ci
      - run: npm run build
      - name: Deploy to Netlify
        uses: netlify/actions/cli@v4
        with:
          args: deploy --dir=dist/restaurante-frontend/browser --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
